<?php defined('BASEPATH') OR exit('No direct script access allowed'); ?>

ERROR - 2024-11-05 17:17:43 --> Query error: Unknown column 'user_id' in 'field list' - Invalid query: INSERT INTO `tracking` (`user_id`, `guest_user_detail`, `trackee_id`, `tracking_type`, `mode_backend`, `share_time`, `guest_user`, `mode`, `start_location`, `start_time`) VALUES ('5256', '{\"first_name\":\"Test\",\"last_name\":\"Kumar\",\"mobile_no\":\"9039014098\"}', '5256', '2', '2', '30', '2', '2', '{\"lat\":\"81.5647636743\",\"lng\":\"91.654434734\",\"power\":\"\",\"time\":\"324325564\",\"date_value\":\"2024-10-30 18:51:30\"}', '2024-11-05 17:17:43')
ERROR - 2024-11-05 17:20:19 --> Query error: Unknown column 'user_id' in 'field list' - Invalid query: INSERT INTO `tracking` (`user_id`, `trackee_id`, `tracking_type`, `mode_backend`, `share_time`, `mode`, `start_location`, `tracker_id`, `start_time`) VALUES ('5256', '5256', '2', '2', '30', '2', '{\"lat\":\"81.5647636743\",\"lng\":\"91.654434734\",\"power\":\"\",\"time\":\"324325564\",\"date_value\":\"2024-10-30 18:51:30\"}', '5251', '2024-11-05 17:20:19')
ERROR - 2024-11-05 17:50:53 --> Query error: Unknown column 'user_id' in 'field list' - Invalid query: INSERT INTO `tracking` (`user_id`, `trackee_id`, `tracking_type`, `mode_backend`, `share_time`, `mode`, `start_location`, `tracker_id`, `start_time`) VALUES ('5256', '5256', '2', '2', '30', '2', '{\"lat\":\"81.5647636743\",\"lng\":\"91.654434734\",\"power\":\"\",\"time\":\"324325564\",\"date_value\":\"2024-10-30 18:51:30\"}', '5251', '2024-11-05 17:50:53')
ERROR - 2024-11-05 17:52:48 --> Query error: Unknown column 'user_id' in 'field list' - Invalid query: INSERT INTO `tracking` (`user_id`, `trackee_id`, `tracking_type`, `mode_backend`, `share_time`, `mode`, `start_location`, `tracker_id`, `start_time`) VALUES ('5256', '5256', '2', '2', '30', '2', '{\"lat\":\"81.5647636743\",\"lng\":\"91.654434734\",\"power\":\"\",\"time\":\"324325564\",\"date_value\":\"2024-10-30 18:51:30\"}', '5251', '2024-11-05 17:52:48')
ERROR - 2024-11-05 17:55:37 --> Query error: Unknown column 'user_id' in 'field list' - Invalid query: INSERT INTO `tracking` (`user_id`, `trackee_id`, `tracking_type`, `mode_backend`, `share_time`, `mode`, `tracker_id`, `start_time`) VALUES ('5256', '5256', '2', '2', '30', '2', '5251', '2024-11-05 17:55:37')
