<?php defined('BASEPATH') OR exit('No direct script access allowed'); ?>

ERROR - 2024-10-30 17:57:15 --> Query error: Unknown column 'user_id' in 'field list' - Invalid query: INSERT INTO `tracking` (`user_id`, `trackee_id`, `tracking_type`, `mode_backend`, `share_time`, `tracker_id`, `start_time`) VALUES ('5256', '5251', '2', '1', '30', '6171', '2024-10-30 17:57:15')
ERROR - 2024-10-30 18:06:33 --> Query error: Unknown column 'user_id' in 'field list' - Invalid query: INSERT INTO `tracking` (`user_id`, `trackee_id`, `tracking_type`, `mode_backend`, `share_time`, `tracker_id`, `start_time`) VALUES ('5256', '5251', '2', '1', '30', '6171', '2024-10-30 18:06:33')
ERROR - 2024-10-30 18:17:03 --> Query error: Unknown column 'user_id' in 'field list' - Invalid query: INSERT INTO `tracking` (`user_id`, `trackee_id`, `tracking_type`, `mode_backend`, `share_time`, `mode`, `tracker_id`, `start_time`) VALUES ('5256', '5251', '1', '1', '30', '1', '6171', '2024-10-30 18:17:03')
ERROR - 2024-10-30 18:52:07 --> Query error: Unknown column 'user_id' in 'field list' - Invalid query: INSERT INTO `tracking` (`user_id`, `trackee_id`, `tracking_type`, `mode_backend`, `share_time`, `mode`, `start_location`, `tracker_id`, `start_time`) VALUES ('5256', '5251', '1', '1', '30', '1', '{\"lat\":\"81.5647636743\",\"lng\":\"91.654434734\",\"power\":\"\",\"time\":\"324325564\",\"date_value\":\"2024-10-30 18:51:30\"}', '6171', '2024-10-30 18:52:07')
ERROR - 2024-10-30 19:13:45 --> Query error: Unknown column 'user_id' in 'field list' - Invalid query: INSERT INTO `tracking` (`user_id`, `trackee_id`, `tracking_type`, `mode_backend`, `share_time`, `mode`, `start_location`, `tracker_id`, `start_time`) VALUES ('5256', '5251', '1', '1', '30', '1', '{\"lat\":\"81.5647636743\",\"lng\":\"91.654434734\",\"power\":\"\",\"time\":\"324325564\",\"date_value\":\"2024-10-30 18:51:30\"}', '6171', '2024-10-30 19:13:45')
ERROR - 2024-10-30 19:31:38 --> Query error: Unknown column 'user_id' in 'field list' - Invalid query: INSERT INTO `tracking` (`user_id`, `trackee_id`, `tracking_type`, `mode_backend`, `share_time`, `mode`, `start_location`, `tracker_id`, `start_time`) VALUES ('5256', '5251', '1', '1', '30', '1', '{\"lat\":\"81.5647636743\",\"lng\":\"91.654434734\",\"power\":\"\",\"time\":\"324325564\",\"date_value\":\"2024-10-30 18:51:30\"}', '6171', '2024-10-30 19:31:38')
ERROR - 2024-10-30 19:32:40 --> Query error: Unknown column 'user_id' in 'field list' - Invalid query: INSERT INTO `tracking` (`user_id`, `trackee_id`, `tracking_type`, `mode_backend`, `share_time`, `mode`, `start_location`, `tracker_id`, `start_time`) VALUES ('5256', '5251', '1', '1', '30', '1', '{\"lat\":\"81.5647636743\",\"lng\":\"91.654434734\",\"power\":\"\",\"time\":\"324325564\",\"date_value\":\"2024-10-30 18:51:30\"}', '6171', '2024-10-30 19:32:40')
ERROR - 2024-10-30 19:36:24 --> Query error: Unknown column 'user_id' in 'field list' - Invalid query: INSERT INTO `tracking` (`user_id`, `trackee_id`, `tracking_type`, `mode_backend`, `share_time`, `mode`, `start_location`, `tracker_id`, `start_time`) VALUES ('5256', '5251', '1', '1', '30', '1', '{\"lat\":\"81.5647636743\",\"lng\":\"91.654434734\",\"power\":\"\",\"time\":\"324325564\",\"date_value\":\"2024-10-30 18:51:30\"}', '6171', '2024-10-30 19:36:24')
ERROR - 2024-10-30 19:42:07 --> Query error: Unknown column 'user_id' in 'field list' - Invalid query: INSERT INTO `tracking` (`user_id`, `trackee_id`, `tracking_type`, `mode_backend`, `share_time`, `mode`, `start_location`, `tracker_id`, `start_time`) VALUES ('5256', '5251', '1', '1', '30', '1', '{\"lat\":\"81.5647636743\",\"lng\":\"91.654434734\",\"power\":\"\",\"time\":\"324325564\",\"date_value\":\"2024-10-30 18:51:30\"}', '6171', '2024-10-30 19:42:07')
